name: "Linter"

on: [ pull_request ]

jobs:
  lint:
    name: Linter (PHP ${{ matrix.php_version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: ['8.0', '8.1', '8.2']
      fail-fast: false  # this ensures all versions are tested even if one fails

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - run: git checkout HEAD^2

      - name: Run Linter
        run: |
          docker run --rm -v $PWD:/app php:${{ matrix.php_version }}-cli-alpine3.18 sh -c \
          "composer install --profile --ignore-platform-reqs && composer lint"
