name: "Tests"

on: [pull_request]
jobs:
  test:
    name: Unit & E2E (PHP 8.2)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        submodules: recursive

    - run: git checkout HEAD^2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile-8.2
        push: false
        tags: database-82
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Start Databases
      run:  |
        docker compose up -d
        sleep 10

    - name: Run Tests
      run: docker compose exec -T tests82 vendor/bin/phpunit --configuration phpunit.xml